services:
  db:
    image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=xx
      - MYSQL_DATABASE=xx
      - MYSQL_USER=xx
      - MYSQL_PASSWORD=xx
    expose:
      - 3306

  wordpress:
    depends_on:
     - db
    image: wordpress:latest
    ports:
      - 8080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=xx
      - WORDPRESS_DB_PASSWORD=xx
      - WORDPRESS_DB_NAME=xx
    volumes:
      - wp-content:/var/www/html/wp-content

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 6969:80
    environment:
      - PMA_HOST=db


volumes:
  db_data:
  wp-content: